<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-RJ4OSE86" name="testNGpractice.AttributeTimeout" tests="3" failures="0" timestamp="14 Sep 2022 16:59:40 GMT" time="2.026" errors="1">
  <testcase name="testCase1" time="2.017" classname="testNGpractice.AttributeTimeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNGpractice.AttributeTimeout.testCase1() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGpractice.AttributeTimeout.testCase1() didn't finish within the time-out 2000
at java.util.concurrent.FutureTask.setException(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase2" time="0.008" classname="testNGpractice.AttributeTimeout"/>
  <testcase name="testCase3" time="0.001" classname="testNGpractice.AttributeTimeout"/>
</testsuite> <!-- testNGpractice.AttributeTimeout -->
